FROM ghcr.io/actions/actions-runner:2.304.0

USER root

# install curl, jq, node.js, git, and unzip
RUN apt-get update && apt-get install -y curl jq nodejs git unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY github-actions-runner/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

USER runner

ENTRYPOINT ["./entrypoint.sh"]
